{{- if eq .Values.nacos.storage.type "mysql"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  {{- with .Values.nacos.storage.db }}
  mysql.db.host: {{.host}}
  mysql.db.name: {{ .name }}
  mysql.port: {{ .port }}
  mysql.user: {{ .username }}
  mysql.password: {{ .password }}
  mysql.param: {{ .param }}
  {{- end }}
  {{- end }}



